# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Tests
        run: bun test

      - name: Build project
        run: bun run build

      # Опціонально: деплой (тільки якщо потрібно, і не для pull request-ів)
      # - name: Deploy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     echo "Deploying..."
